name: CI — Docker Build & Push

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  ACR_NAME: acrtodoappsiddharth1
  IMAGE_NAME: myapp
  IMAGE_TAG: latest

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    environment: Dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: Azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENTID }}
          tenant-id: ${{ secrets.AZURE_TENANTID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTIONID }}

      - name: Login to ACR
        run: az acr login --name $ACR_NAME

      - name: Build and Push Docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: |
            ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
