name: CI — Docker Build & Push

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  az_login:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: Azure/login@v3
        with:
          # ClientId of the Azure Service principal created.
          client-id: ${{ secrets.AZURE_CLIENTID }}
          # TenantId of the Azure Service principal created.
          tenant-id: ${{ secrets.AZURE_TENANTID }}
          # Azure subscriptionId
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTIONID }}
